name: Login en azure con Bash

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login en Azure (Bash)
        run: | 
          az login --username ${{ secrets.AZ_USERNAME }} -- password $ secrets.AZ_PASS }}
