name: Objetivo 3

on:
  pull_request:
    types: [opened, reopened]

jobs:
  generar-issue:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Crear issue
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.isues.create({
            repo: context.repo.repo,
            owner: context.repo.owner,
            tittle: "Issue creada",
            body: "Prueba de creación automática de issues",
          )};
          console.log(response.data.html_url);
          core.set0up("issue_url",response.data.html_url)

    - name: Asignar issue
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            assignees: ["icasado01"]
          )};
