name: Objetivo 5 - Login AZ (bash)

on:
  pull_request:
    types: [opened, reopened]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login en Azure (Bash)
        run: | 
          az login --service-principal -u ${{ secrets.AZ_CLIENT_ID }} -p${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZ_TENANT_ID }}
          if [ $? -eq 0 ]; then
            echo "Azure login successful!"
          else
            echo "Azure login failed!"
            exit 1
          fi
