name: Objetivo 4

on:
  workflow_dispatch:
    inputs:
      operacion:
        description: "Elige una operación [suma, resta, multiplicacion, division]"
        required: true
      num1:
        description: "Inserte un numero"
        required: true
      num2:
        description: "Inserte otro numero"
        required: true

jobs:
  calcular:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar operacion
        run: bash ./scripts/calculadora.sh ${{ github.event.inputs.operacion }} ${{ github.event.inputs.valor1 }} ${{ github.event.inputs.valor2 }}
