name: Objetivo 3

on:
  pull_request:
    types: [opened, reopened]

jobs:
  generar-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Crear issue
        run: |
          gh issue create --title "Issue creada" --body "Prueba de creación automática de issues"
      
      - name: Asignar issue
        run: |
          gh issue add-assignees ${{ github.event.number }} --assignee icasado01
